---
# tasks file for docker_on_ec2

- name: Configuring Docker Repository
  yum_repository:
    name:  Docker
    description: "docker"
    baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
    gpgcheck: no

- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: list of yum packages that are needed to be installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - python-pip
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - amazon-linux-extras

- name: Add extras repository
  shell: yum-config-manager --enable extras

  #- name: install latest version of selinux
  #shell: yum install http://vault.centos.org/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm

- name: Install docker-ce
  package: 
    name: "docker-ce-18.09.1-3.el7.x86_64"
    state: present

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Python pip packages that are needed to be installed
  pip:
    name: "{{ packages }}"
  vars:
    packages:
    - boto
    - boto3
    - docker-compose
